const ACTION_TYPES = Object.freeze({
  /* test */
  TEST_DISPATCH: 'TEST_DISPATCH',

  /* top-level action */
  PRESS_KEYPAD: 'PRESS_KEYPAD',

  /* keypresses */
  CLEAR_MEMORY: 'CLEAR_MEMORY',
  RETRIEVE_MEMORY: 'RETRIEVE_MEMORY',
  STORE_MEMORY: 'STORE_MEMORY',
  ADD_OPERATION: 'ADD_OPERATION',
  CLEAR_ALL: 'CLEAR_ALL',
  RUN_OPERATIONS: 'RUN_OPERATIONS',
  ADD_DECIMAL: 'ADD_DECIMAL',
  ADD_NUMBER: 'ADD_NUMBER'
})

export default ACTION_TYPES
